name = "CommutatorTheorem"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CommutatorTheorem", "PavingSeparation", "KadisonSinger"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc1"

[[lean_lib]]
name = "CommutatorTheorem"

[[lean_lib]]
name = "PavingSeparation"

[lean_lib.leanOptions]
autoImplicit = false

[[lean_lib]]
name = "KadisonSinger"

[lean_lib.leanOptions]
autoImplicit = false
