import CommutatorTheorem.NoEpsilon.Main
import PavingSeparation.Theorem1
import KadisonSinger.Main

/-!
# Declaration index for the revised 23-page paper (checked 2026-09-07)

The paper's numbering is recorded in README.md. Existing declaration names are stable.
This file checks that every linked declaration is available and audits the listed entry points.
It does not equate differently normalized statements or assert coverage of the paper's prose.
-/

#check NoEpsilon.uniformCommutatorBound
#check PavingSeparation.paving_commutator_separation
#check PavingSeparation.finFamily_lambdaA_lower_bound
#check NoEpsilon.hermitianUnitaryCommutatorBound
#check NoEpsilon.HermitianUnitaryCommutatorBound
#check NoEpsilon.adaptiveTwoCommutatorBound
#check NoEpsilon.AdaptiveTwoCommutatorBound
#check NoEpsilon.identityCorner_bounded_from_whole_norm
#check NoEpsilon.identityCornerNormBudget
#check NoEpsilon.exists_sylvester_solution
#check NoEpsilon.exists_sylvester_solution_scalar_centers
#check NoEpsilon.Absorption.identity_corner_absorption
#check NoEpsilon.MSSFinite.finite_mss
#check NoEpsilon.MSSFinite.finite_mss_supported
#check NoEpsilon.MSSFinite.finite_mss_positive_probability
#check KadisonSinger.kadison_singer_state_extension
#check KadisonSinger.kadison_singer
#check NoEpsilon.MSSPadding.finite_mss_le
#check NoEpsilon.highMass_compression_contains_disk
#check NoEpsilon.exists_unit_neutral_large_image_of_numericalRange
#check NoEpsilon.highMass_bounded_commutator
#check NoEpsilon.commutator_of_normalized
#check NoEpsilon.ThreeHermitian.exists_diagonal_control
#check NoEpsilon.LowMassPaving.exists_transversals
#check NoEpsilon.LowMassPaving.pairedHalfSelection
#check NoEpsilon.normalized_low_mass_paving
#check NoEpsilon.LowMassPaving.exists_paving_basis
#check NoEpsilon.BlockAssembly.assemble_fixed_constants
#check PavingSeparation.skew_mul_self
#check PavingSeparation.skew_offdiag_eq_one_or_neg_one
#check PavingSeparation.PlanarEnergy.energy_lower_bound
#check PavingSeparation.lambdaCosts
#check PavingSeparation.lambdaA
#check PavingSeparation.lambdaClass
#check PavingSeparation.lambdaM
#check PavingSeparation.pavingMinimum
#check PavingSeparation.exists_pavingMinimum
#check PavingSeparation.compression_norm_eq_principal
#check NoEpsilon.HasHighTraceMass
#check NoEpsilon.UniformCommutatorBound
#check NoEpsilon.globalNormBudget
#check PavingSeparation.family_diag
#check PavingSeparation.family_isHermitian
#check PavingSeparation.family_mul_self
#check PavingSeparation.family_norm
#check PavingSeparation.card_cube
#check PavingSeparation.pavingMinimum_dyadic_ratio
#check PavingSeparation.exists_uniform_family_paving
#check PavingSeparation.normalCost
#check PavingSeparation.normalCost_eq_lambdaA
#check PavingSeparation.twoNormalCost
#check PavingSeparation.family_twoNormalCost
#check PavingSeparation.normal_factors_commutator
#check PavingSeparation.flip_norm
#check PavingSeparation.normalSecond_norm
#check PavingSeparation.separationLowerBound_sqrt
#check PavingSeparation.lambdaM_four_pow_lower_bound
#check PavingSeparation.lambdaM_four_pow_sqrt_lower_bound
#check PavingSeparation.lambdaM_unbounded
#check PavingSeparation.lambdaM_not_bddAbove
#check PavingSeparation.section5_finite_but_unbounded
#check PavingSeparation.diagonalCost
#check PavingSeparation.skewMatrix
#check PavingSeparation.skew_zero
#check PavingSeparation.skew_succ
#check PavingSeparation.skew_conj_apply
#check PavingSeparation.skew_transpose
#check PavingSeparation.skew_diag
#check PavingSeparation.pavingMatrix
#check PavingSeparation.family_offdiag_norm_sq
#check PavingSeparation.family_trace
#check PavingSeparation.Foundation.hsNorm_le_sqrt_n_mul_opNorm
#check PavingSeparation.family_compression_lower
#check PavingSeparation.pavingMinimum_ceiling_lower
#check PavingSeparation.dyadic_family_compression_norm
#check PavingSeparation.dyadic_pavingNorm
#check PavingSeparation.family_paving_card_lower
#check PavingSeparation.DiagonalCost.diagonal_commutator_cost_sq
#check PavingSeparation.DiagonalCost.diagonal_commutator_cost
#check PavingSeparation.DiagonalCost.isDiag_commutator_product_cost
#check PavingSeparation.family_diagonalCost_lower_bound
#check PavingSeparation.commutator_cost_lower
#check PavingSeparation.section5_unrestricted
#check NoEpsilon.uniformCommutatorBound_euclideanOperatorNorm
#check NoEpsilon.uniformCommutatorBound_iff_euclideanOperatorNorm
#check NoEpsilon.uniformCommutatorBound_of_lowMassBlocksAt
#check NoEpsilon.lowMassPavingInput_proved
#check NoEpsilon.GlobalAssembly.assemble_with_leftovers
#check NoEpsilon.assemble_one_with_leftovers
#check NoEpsilon.zeroDiag_small_commutator
#check NoEpsilon.Steinitz.exists_order
#check NoEpsilon.SteinitzGrouping.exists_trace_controlled_groups
#check NoEpsilon.ThreeHermitian.exists_almost_hollow
#check NoEpsilon.MSSScaled.finite_mss_scaled
#check NoEpsilon.LowMassPaving.binary_recurrence_leaf_bound
#check NoEpsilon.LowMassPaving.transversalConstant_twelve_add_four_lt
#check NoEpsilon.exists_riccati_fixedPoint_large_scale
#check NoEpsilon.Absorption.eliminate_finset
#check NoEpsilon.highMass_exists_neutral_frame
#check NoEpsilon.highMass_exists_diagonal_bridge
#check NoEpsilon.Absorption.firstBudget
#check NoEpsilon.Absorption.stepBudget
#check NoEpsilon.Absorption.absorptionBudget
#check NoEpsilon.highMassNormBudget
#check NoEpsilon.globalNormBudget_closes

#print axioms NoEpsilon.uniformCommutatorBound
#print axioms NoEpsilon.uniformCommutatorBound_euclideanOperatorNorm
#print axioms NoEpsilon.MSSFinite.finite_mss
#print axioms NoEpsilon.MSSFinite.finite_mss_supported
#print axioms NoEpsilon.MSSFinite.finite_mss_positive_probability
#print axioms KadisonSinger.kadison_singer_state_extension
#print axioms KadisonSinger.kadison_singer
#print axioms NoEpsilon.normalized_low_mass_paving
#print axioms PavingSeparation.paving_commutator_separation
#print axioms PavingSeparation.finFamily_lambdaA_lower_bound
#print axioms PavingSeparation.lambdaM_unbounded
#print axioms PavingSeparation.PlanarEnergy.energy_lower_bound
