import CommutatorTheorem.Epsilon.Main
import CommutatorTheorem.Epsilon.BTPrerequisites
import CommutatorTheorem.Epsilon.BTDirect
import CommutatorTheorem.Epsilon.BTCardTwo
import CommutatorTheorem.Epsilon.BTCardThree
import CommutatorTheorem.Epsilon.BTInterlacing
import CommutatorTheorem.Epsilon.BTInterlacingConverse
import CommutatorTheorem.Epsilon.BTFellPair
import CommutatorTheorem.Epsilon.BTMixedDet
import CommutatorTheorem.Epsilon.BTMixedDeterminantal
import CommutatorTheorem.Epsilon.BTMDPSelection
import CommutatorTheorem.Epsilon.BTMDPStability
import CommutatorTheorem.Epsilon.BTMDPDeletionIdentity
import CommutatorTheorem.Epsilon.BTMDPJointControl
import CommutatorTheorem.Epsilon.BTExactSecondMoment
import CommutatorTheorem.Epsilon.BTExactRootInterval
import CommutatorTheorem.Epsilon.BTMDPRootShrinkAssembly
import CommutatorTheorem.Epsilon.BTMDPFinalAssembly
import CommutatorTheorem.Epsilon.BTDeterminantStability
import CommutatorTheorem.Epsilon.BTHermitianDetPDeriv
import CommutatorTheorem.Epsilon.BTRealStabilityClosure
import CommutatorTheorem.Epsilon.BTRSStabilityBridge
import CommutatorTheorem.Epsilon.BTMDPInterlacingFromConvex
import CommutatorTheorem.Epsilon.BTRSExactMDPHarness
import CommutatorTheorem.Epsilon.BTRSAnalyticCoreAssembly
import CommutatorTheorem.Epsilon.BTRSBaseExpansion
import CommutatorTheorem.Epsilon.BTRSBaseExpansionClose
import CommutatorTheorem.Epsilon.BTRootShrinkArithmetic
import CommutatorTheorem.Epsilon.BTRootShrinking
import CommutatorTheorem.Epsilon.BTRootMoment
import CommutatorTheorem.Epsilon.BTRootShrinkingClose
import CommutatorTheorem.Epsilon.BTRootEndpoint
import CommutatorTheorem.Epsilon.BTJointReduction
import CommutatorTheorem.Epsilon.BTLibraryRoute
import CommutatorTheorem.Epsilon.BTDirectProof
import CommutatorTheorem.Epsilon.BTLeafSpectral
import CommutatorTheorem.CommutatorConjecture

/-!
# Commutator-theorem formalization harness

This file is a small, stable entry point for checking the live proof chain and
the two Phase-5 interfaces recovered from the JOS argument.  It deliberately
contains no replacement axioms and no proof placeholders.
-/

open CommutatorTheorem Pow4Bootstrap

#check CommutatorTheorem.central_submatrix_large_epsilon
#check CommutatorTheorem.central_submatrix_card_le_one
#check CommutatorTheorem.central_submatrix_card_le_two
#check CommutatorTheorem.central_submatrix_card_le_three
#check CommutatorTheorem.central_submatrix_of_small_epsilon_core
#check CommutatorTheorem.finiteUniform_markov
#check CommutatorTheorem.setFamily_card_le_sum_choose
#check CommutatorTheorem.principalCompression_norm_le
#check CommutatorTheorem.canonical_trivial_paving
#check CommutatorTheorem.canonical_terminal_paving_zero
#check CommutatorTheorem.SelectedHalfLambdaDescent
#check CommutatorTheorem.RealRooted.derivative
#check CommutatorTheorem.HasCommonInterlacer.toUpperCertificate
#check CommutatorTheorem.HasCommonInterlacer.monic_polynomialWeightedSum
#check CommutatorTheorem.exists_weightedSum_root_between_interlacerRoots
#check CommutatorTheorem.exists_largestRoot_and_member_below
#check CommutatorTheorem.realRooted_polynomialWeightedSum_of_commonInterlacer
#check CommutatorTheorem.HasCommonInterlacer.exists_largestRoot_and_member_below_automatic
#check CommutatorTheorem.BTInterlacingConverse.hasCommonInterlacer_of_pairwise
#check CommutatorTheorem.BTInterlacingConverse.finite_fell_of_pair_fell
#check CommutatorTheorem.BTInterlacingConverse.pair_fell_natDegree_one
#check CommutatorTheorem.BTFellPair.pair_fell_natDegree_two
#check CommutatorTheorem.BTFellPair.finite_fell_natDegree_two
#check CommutatorTheorem.BTMixedDet.averageCharpoly_monic
#check CommutatorTheorem.BTMixedDet.averageSecondNewtonNumerator_eq
#check CommutatorTheorem.BTMixedDet.averageCharpoly_coeff_sub_two_eq_inv_sq_mul
#check CommutatorTheorem.BTMixedDeterminantal.coloringPolynomial_monic
#check CommutatorTheorem.BTMixedDeterminantal.mixedDeterminantalPolynomial_monic
#check CommutatorTheorem.BTMixedDeterminantal.mixedDeterminantalPolynomial_nextCoeff_eq_zero
#check CommutatorTheorem.BTMDPSelection.realMixedDeterminantalPolynomial_monic
#check CommutatorTheorem.BTMDPSelection.realMixedDeterminantalPolynomial_nextCoeff_eq_zero
#check CommutatorTheorem.BTMDPSelection.DeletionInterlacingTree.select_subset
#check CommutatorTheorem.BTMDPSelection.prefixConditionalAverage_succ_eq_weightedSum
#check CommutatorTheorem.BTMDPSelection.select_coloring_from_root
#check CommutatorTheorem.BTMDPStability.charpoly_derivative_eq_sum_principal_fin_succ
#check CommutatorTheorem.BTMDPStability.derivative_realColoringPolynomial
#check CommutatorTheorem.BTMDPStability.normalizedConditionalMDP_parent_average_of_deletionIdentity
#check CommutatorTheorem.BTMDPStability.PrefixMDPChildrenCommon
#check CommutatorTheorem.BTMDPStability.realRooted_prefixConditionalAverage_of_childrenCommon
#check CommutatorTheorem.BTMDPStability.select_coloring_of_childrenCommon
#check CommutatorTheorem.BTMDPDeletionIdentity.coloringCoordinateEquiv
#check CommutatorTheorem.BTMDPDeletionIdentity.sum_coloring_colorFiber_eq_sum_deletion_extensions
#check CommutatorTheorem.BTMDPDeletionIdentity.derivative_realMixedDeterminantalPolynomial_eq_sum_deleteFamilyAt
#check CommutatorTheorem.BTMDPDeletionIdentity.mdpDeletionDerivativeIdentity_of_pos
#check CommutatorTheorem.BTMDPJointControl.singleMatrixMDP_closedForm
#check CommutatorTheorem.BTMDPJointControl.MDPJointRootMonotonicity
#check CommutatorTheorem.BTMDPJointControl.realCharpoly_rootUpperBound_of_singleMatrixMDP
#check CommutatorTheorem.BTMDPJointControl.joint_realCharpoly_rootUpperBound_of_MDP
#check CommutatorTheorem.BTExactSecondMoment.realMixedDeterminantalPolynomial_coeff_sub_two
#check CommutatorTheorem.BTExactSecondMoment.sum_sq_roots_realMixedDeterminantalPolynomial_real
#check CommutatorTheorem.BTExactSecondMoment.rootMeanSquare_realMixedDeterminantalPolynomial_le_inv
#check CommutatorTheorem.BTExactRootInterval.abs_root_realColoringPolynomial_le_one
#check CommutatorTheorem.BTExactRootInterval.realMixedDeterminantalPolynomial_rootUpperBound_one
#check CommutatorTheorem.BTExactRootInterval.realMixedDeterminantalPolynomial_rootLowerBound_neg_one
#check CommutatorTheorem.BTExactRootInterval.realMixedDeterminantalPolynomial_root_mem_unitInterval
#check CommutatorTheorem.BTMDPRootShrinkAssembly.exactMDP_iterateDerivative_strictRootUpperBound
#check CommutatorTheorem.BTMDPRootShrinkAssembly.exists_restrictedMDP_strictRootUpperBound
#check CommutatorTheorem.BTDeterminantStability.det_diagonal_sub_hermitian_ne_zero
#check CommutatorTheorem.BTDeterminantStability.realHermitianDetPoly_realStable
#check CommutatorTheorem.BTRealStabilityClosure.UnivariateStableOrZero.derivative
#check CommutatorTheorem.BTRealStabilityClosure.MvStableOrZero.diagonalize
#check CommutatorTheorem.BTRealStabilityClosure.MultivariateGaussLucasHurwitz
#check CommutatorTheorem.BTRealStabilityClosure.realRooted_of_map_upperStable
#check CommutatorTheorem.BTRSStabilityBridge.iteratedPDeriv_realHermitianDetProduct_stable
#check CommutatorTheorem.BTRSStabilityBridge.realRooted_diagonal_iteratedPDeriv_detProduct
#check CommutatorTheorem.BTMDPInterlacingFromConvex.mdpConditionalInterlacing_of_rootDisjointFell
#check CommutatorTheorem.BTRSExactMDPHarness.RSExactMDPBaseDeletionExpansion
#check CommutatorTheorem.BTRSBaseExpansionClose.rsExactMDPFactorialBaseIdentity
#check CommutatorTheorem.BTRSBaseExpansionClose.rsExactMDPBaseDeletionExpansion
#check CommutatorTheorem.BTRSExactMDPHarness.rsExactConditionalMDPExpansion_of_baseDeletion
#check CommutatorTheorem.BTRSExactMDPHarness.mdpConditionalInterlacing_of_rsExpansion
#check CommutatorTheorem.BTRSAnalyticCoreAssembly.btMDPAnalyticCore_of_rsStability
#check CommutatorTheorem.BTRSAnalyticCoreAssembly.fourHermitianUpperSelection24_of_rsStability
#check CommutatorTheorem.BTRSAnalyticCoreAssembly.bourgainTzafriri_of_rsStability
#check CommutatorTheorem.BTMDPInterlacingFromConvex.normalizedConditionalMDP_isMonicOfDegree
#check CommutatorTheorem.BTMDPInterlacingFromConvex.mdpConditionalInterlacing_of_rootDisjointFell
#check CommutatorTheorem.BTRSExactMDPHarness.derivative_diagonalizeReal
#check CommutatorTheorem.BTRSExactMDPHarness.rsExactConditionalMDPExpansion_of_baseDeletion
#check CommutatorTheorem.BTRSExactMDPHarness.mdpConditionalInterlacing_of_rsExpansion
#check CommutatorTheorem.BTRSAnalyticCoreAssembly.btMDPAnalyticCore_of_rsBaseDeletion
#check CommutatorTheorem.BTRSAnalyticCoreAssembly.bourgainTzafriri_of_rsBaseDeletion
#check CommutatorTheorem.jointRI_rootShrink_constant
#check CommutatorTheorem.jointRI_rootShrink_constant_of_c_le
#check CommutatorTheorem.rootBarrier_curvature_identity
#check CommutatorTheorem.reciprocal_gap_barrier_sum
#check CommutatorTheorem.iterate_derivative_rootUpperBound_of_barrier_steps
#check CommutatorTheorem.derivativeBarrierStep_of_realRooted
#check CommutatorTheorem.derivativeBarrierStep_of_realRooted_le
#check CommutatorTheorem.iterate_derivative_rootUpperBound_of_initial_barrier
#check CommutatorTheorem.sum_sq_roots_eq_neg_two_mul_coeff_sub_two
#check CommutatorTheorem.rootBarrierPotential_le_of_mean_zero_second_moment
#check CommutatorTheorem.rootShrinkMomentObjective_at_optimum
#check CommutatorTheorem.one_le_optimal_rootMoment_barrier
#check CommutatorTheorem.rootUpperBound_iterate_derivative_of_mean_zero_second_moment
#check CommutatorTheorem.rootUpperBound_iterate_derivative_at_admissibility_endpoint
#check CommutatorTheorem.rootUpperBound_iterate_derivative_of_second_moment_zero
#check CommutatorTheorem.rootUpperBound_iterate_derivative_of_mean_zero_second_moment_le
#check CommutatorTheorem.JointRestrictedInvertibility
#check CommutatorTheorem.jointRestrictedInvertibility_smallEpsilonCore
#check CommutatorTheorem.bourgain_tzafriri_central_submatrix_of_jointRestrictedInvertibility
#check CommutatorTheorem.OneSidedJointRestrictedInvertibility
#check CommutatorTheorem.jointRestrictedInvertibility_of_oneSided
#check CommutatorTheorem.bourgain_tzafriri_central_submatrix_of_oneSided
#check CommutatorTheorem.QuantitativeZeroDiagonalPaving
#check CommutatorTheorem.central_submatrix_of_quantitativePaving
#check CommutatorTheorem.FourHermitianUpperSelection24
#check CommutatorTheorem.jointRestrictedInvertibility_of_fourHermitianUpperSelection24
#check CommutatorTheorem.bourgainTzafriri_of_fourHermitianUpperSelection24
#check CommutatorTheorem.JointHermitianPaving24
#check CommutatorTheorem.principalCompression_le_of_realColoringPolynomial_rootUpperBound
#check CommutatorTheorem.exists_submatrix_le_of_leaf_rootUpperBound_of_card_le
#check CommutatorTheorem.FourHermitianCommonRootSelection24
#check CommutatorTheorem.fourHermitianUpperSelection24_of_commonRootSelection
#check CommutatorTheorem.BTMDPFinalAssembly.BTMDPAnalyticCore
#check CommutatorTheorem.BTMDPFinalAssembly.fourHermitianCommonRootSelection24_of_mdpAnalyticCore
#check CommutatorTheorem.BTMDPFinalAssembly.fourHermitianUpperSelection24_of_mdpAnalyticCore
#check CommutatorTheorem.BTMDPFinalAssembly.bourgainTzafriri_of_mdpAnalyticCore
#check CommutatorTheorem.BTMDPFinalAssembly.bourgain_tzafriri_central_submatrix_of_mdpAnalyticCore
#check Pow4Bootstrap.lambdaA_two_block_decomp_asym
#check CommutatorTheorem.lambdaA_two_block_decomp_asym_reindex
#check CommutatorTheorem.convergent_eta_product_bound
#check CommutatorTheorem.lambdaA_BT_small_side_uniform
#check CommutatorTheorem.lambdaM_two_pow4_claim2_recursion
#check CommutatorTheorem.lambdaM_pow4_succ_claim2_recursion
#check CommutatorTheorem.lambdaM_pow4_claim2_recursion
#check CommutatorTheorem.lambdaM_pow4_geometric_bound
#check CommutatorTheorem.zeroDiag_commutator_bound
#check CommutatorTheorem.zeroDiag_commutator_bound_diagonal
#check CommutatorTheorem.main_commutator_theorem
#check CommutatorTheorem.main_commutator_theorem_normal
#check CommutatorTheorem.AbsoluteCommutatorConjecture

example (K : ℝ) (hK : 0 < K) :
    ∃ Pbound : ℝ, 1 ≤ Pbound ∧
      ∀ (a b : ℕ),
        ∏ s ∈ Finset.Ico a b,
          (1 + K / ((s : ℝ) + 2) ^ 2) ≤ Pbound :=
  CommutatorTheorem.convergent_eta_product_bound K hK

/- These reports make the remaining trusted assumptions visible in CI logs. -/
#print axioms CommutatorTheorem.central_submatrix_large_epsilon
#print axioms CommutatorTheorem.central_submatrix_card_le_one
#print axioms CommutatorTheorem.central_submatrix_card_le_two
#print axioms CommutatorTheorem.central_submatrix_card_le_three
#print axioms CommutatorTheorem.central_submatrix_of_small_epsilon_core
#print axioms CommutatorTheorem.canonical_trivial_paving
#print axioms CommutatorTheorem.canonical_terminal_paving_zero
#print axioms CommutatorTheorem.RealRooted.derivative
#print axioms CommutatorTheorem.realRooted_polynomialWeightedSum_of_commonInterlacer
#print axioms CommutatorTheorem.HasCommonInterlacer.exists_largestRoot_and_member_below_automatic
#print axioms CommutatorTheorem.BTInterlacingConverse.hasCommonInterlacer_of_pairwise
#print axioms CommutatorTheorem.BTInterlacingConverse.finite_fell_of_pair_fell
#print axioms CommutatorTheorem.BTInterlacingConverse.pair_fell_natDegree_one
#print axioms CommutatorTheorem.BTFellPair.pair_fell_natDegree_two
#print axioms CommutatorTheorem.BTFellPair.finite_fell_natDegree_two
#print axioms CommutatorTheorem.BTMixedDet.averageCharpoly_monic
#print axioms CommutatorTheorem.BTMixedDet.averageSecondNewtonNumerator_eq
#print axioms CommutatorTheorem.BTMixedDet.averageCharpoly_coeff_sub_two_eq_inv_sq_mul
#print axioms CommutatorTheorem.BTMixedDeterminantal.mixedDeterminantalPolynomial_monic
#print axioms CommutatorTheorem.BTMixedDeterminantal.mixedDeterminantalPolynomial_nextCoeff_eq_zero
#print axioms CommutatorTheorem.BTMDPSelection.realMixedDeterminantalPolynomial_monic
#print axioms CommutatorTheorem.BTMDPSelection.realMixedDeterminantalPolynomial_nextCoeff_eq_zero
#print axioms CommutatorTheorem.BTMDPSelection.DeletionInterlacingTree.select_subset
#print axioms CommutatorTheorem.BTMDPSelection.prefixConditionalAverage_succ_eq_weightedSum
#print axioms CommutatorTheorem.BTMDPSelection.select_coloring_from_root
#print axioms CommutatorTheorem.BTMDPStability.charpoly_derivative_eq_sum_principal_fin_succ
#print axioms CommutatorTheorem.BTMDPStability.derivative_realColoringPolynomial
#print axioms CommutatorTheorem.BTMDPStability.normalizedConditionalMDP_parent_average_of_deletionIdentity
#print axioms CommutatorTheorem.BTMDPStability.realRooted_prefixConditionalAverage_of_childrenCommon
#print axioms CommutatorTheorem.BTMDPStability.select_coloring_of_childrenCommon
#print axioms CommutatorTheorem.BTMDPDeletionIdentity.sum_coloring_colorFiber_eq_sum_deletion_extensions
#print axioms CommutatorTheorem.BTMDPDeletionIdentity.derivative_realMixedDeterminantalPolynomial_eq_sum_deleteFamilyAt
#print axioms CommutatorTheorem.BTMDPDeletionIdentity.mdpDeletionDerivativeIdentity_of_pos
#print axioms CommutatorTheorem.BTMDPJointControl.singleMatrixMDP_closedForm
#print axioms CommutatorTheorem.BTMDPJointControl.realCharpoly_rootUpperBound_of_singleMatrixMDP
#print axioms CommutatorTheorem.BTMDPJointControl.joint_realCharpoly_rootUpperBound_of_MDP
#print axioms CommutatorTheorem.BTExactSecondMoment.realMixedDeterminantalPolynomial_coeff_sub_two
#print axioms CommutatorTheorem.BTExactSecondMoment.sum_sq_roots_realMixedDeterminantalPolynomial_real
#print axioms CommutatorTheorem.BTExactSecondMoment.rootMeanSquare_realMixedDeterminantalPolynomial_le_inv
#print axioms CommutatorTheorem.BTExactRootInterval.abs_root_realColoringPolynomial_le_one
#print axioms CommutatorTheorem.BTExactRootInterval.realMixedDeterminantalPolynomial_rootUpperBound_one
#print axioms CommutatorTheorem.BTExactRootInterval.realMixedDeterminantalPolynomial_rootLowerBound_neg_one
#print axioms CommutatorTheorem.BTExactRootInterval.realMixedDeterminantalPolynomial_root_mem_unitInterval
#print axioms CommutatorTheorem.BTMDPRootShrinkAssembly.exactMDP_iterateDerivative_strictRootUpperBound
#print axioms CommutatorTheorem.BTMDPRootShrinkAssembly.exists_restrictedMDP_strictRootUpperBound
#print axioms CommutatorTheorem.BTDeterminantStability.det_diagonal_sub_hermitian_ne_zero
#print axioms CommutatorTheorem.BTDeterminantStability.realHermitianDetPoly_realStable
#print axioms CommutatorTheorem.BTHermitianDetPDeriv.pderiv_det_eq_sum_updateCol
#print axioms CommutatorTheorem.BTHermitianDetPDeriv.pderiv_hermitianDetPoly_fin_succ
#print axioms CommutatorTheorem.BTRealStabilityClosure.UnivariateStableOrZero.derivative
#print axioms CommutatorTheorem.BTRealStabilityClosure.MvStableOrZero.diagonalize
#print axioms CommutatorTheorem.BTRealStabilityClosure.realRooted_of_map_upperStable
#print axioms CommutatorTheorem.BTRSStabilityBridge.iteratedPDeriv_realHermitianDetProduct_stable
#print axioms CommutatorTheorem.BTRSStabilityBridge.realRooted_diagonal_iteratedPDeriv_detProduct
#print axioms CommutatorTheorem.BTMDPInterlacingFromConvex.mdpConditionalInterlacing_of_rootDisjointFell
#print axioms CommutatorTheorem.BTRSExactMDPHarness.rsExactConditionalMDPExpansion_of_baseDeletion
#print axioms CommutatorTheorem.BTRSExactMDPHarness.mdpConditionalInterlacing_of_rsExpansion
#print axioms CommutatorTheorem.BTRSAnalyticCoreAssembly.btMDPAnalyticCore_of_rsStability
#print axioms CommutatorTheorem.BTRSAnalyticCoreAssembly.fourHermitianUpperSelection24_of_rsStability
#print axioms CommutatorTheorem.BTRSAnalyticCoreAssembly.bourgainTzafriri_of_rsStability
#print axioms CommutatorTheorem.BTMDPInterlacingFromConvex.normalizedConditionalMDP_isMonicOfDegree
#print axioms CommutatorTheorem.BTMDPInterlacingFromConvex.mdpConditionalInterlacing_of_rootDisjointFell
#print axioms CommutatorTheorem.BTRSExactMDPHarness.derivative_diagonalizeReal
#print axioms CommutatorTheorem.BTRSExactMDPHarness.rsExactConditionalMDPExpansion_of_baseDeletion
#print axioms CommutatorTheorem.BTRSExactMDPHarness.mdpConditionalInterlacing_of_rsExpansion
#print axioms CommutatorTheorem.BTRSAnalyticCoreAssembly.btMDPAnalyticCore_of_rsBaseDeletion
#print axioms CommutatorTheorem.BTRSAnalyticCoreAssembly.bourgainTzafriri_of_rsBaseDeletion
#print axioms CommutatorTheorem.BTRSBaseExpansion.not_RSExactMDPBaseDeletionExpansionUnrestricted
#print axioms CommutatorTheorem.BTRSBaseExpansionClose.rsExactMDPFactorialBaseIdentity
#print axioms CommutatorTheorem.BTRSBaseExpansionClose.rsExactMDPBaseDeletionExpansion
#print axioms CommutatorTheorem.jointRI_rootShrink_constant
#print axioms CommutatorTheorem.jointRI_rootShrink_constant_of_c_le
#print axioms CommutatorTheorem.rootBarrier_curvature_identity
#print axioms CommutatorTheorem.reciprocal_gap_barrier_sum
#print axioms CommutatorTheorem.iterate_derivative_rootUpperBound_of_barrier_steps
#print axioms CommutatorTheorem.derivativeBarrierStep_of_realRooted
#print axioms CommutatorTheorem.derivativeBarrierStep_of_realRooted_le
#print axioms CommutatorTheorem.iterate_derivative_rootUpperBound_of_initial_barrier
#print axioms CommutatorTheorem.sum_sq_roots_eq_neg_two_mul_coeff_sub_two
#print axioms CommutatorTheorem.rootBarrierPotential_le_of_mean_zero_second_moment
#print axioms CommutatorTheorem.rootShrinkMomentObjective_at_optimum
#print axioms CommutatorTheorem.one_le_optimal_rootMoment_barrier
#print axioms CommutatorTheorem.rootUpperBound_iterate_derivative_of_mean_zero_second_moment
#print axioms CommutatorTheorem.rootUpperBound_iterate_derivative_at_admissibility_endpoint
#print axioms CommutatorTheorem.rootUpperBound_iterate_derivative_of_second_moment_zero
#print axioms CommutatorTheorem.rootUpperBound_iterate_derivative_of_mean_zero_second_moment_le
#print axioms CommutatorTheorem.jointRestrictedInvertibility_smallEpsilonCore
#print axioms CommutatorTheorem.bourgain_tzafriri_central_submatrix_of_jointRestrictedInvertibility
#print axioms CommutatorTheorem.jointRestrictedInvertibility_of_oneSided
#print axioms CommutatorTheorem.bourgain_tzafriri_central_submatrix_of_oneSided
#print axioms CommutatorTheorem.central_submatrix_of_quantitativePaving
#print axioms CommutatorTheorem.jointRestrictedInvertibility_of_fourHermitianUpperSelection24
#print axioms CommutatorTheorem.bourgainTzafriri_of_fourHermitianUpperSelection24
#print axioms CommutatorTheorem.principalCompression_le_of_realColoringPolynomial_rootUpperBound
#print axioms CommutatorTheorem.exists_submatrix_le_of_leaf_rootUpperBound_of_card_le
#print axioms CommutatorTheorem.fourHermitianUpperSelection24_of_commonRootSelection
#print axioms CommutatorTheorem.BTMDPFinalAssembly.fourHermitianCommonRootSelection24_of_mdpAnalyticCore
#print axioms CommutatorTheorem.BTMDPFinalAssembly.fourHermitianUpperSelection24_of_mdpAnalyticCore
#print axioms CommutatorTheorem.BTMDPFinalAssembly.bourgainTzafriri_of_mdpAnalyticCore
#print axioms CommutatorTheorem.BTMDPFinalAssembly.bourgain_tzafriri_central_submatrix_of_mdpAnalyticCore
#print axioms CommutatorTheorem.lambdaM_pow4_claim2_recursion
#print axioms CommutatorTheorem.lambdaM_pow4_geometric_bound
#print axioms CommutatorTheorem.main_commutator_theorem
#print axioms CommutatorTheorem.main_commutator_theorem_normal
